#!/usr/bin/env python3
"""
Script para verificar que las tarjetas del dashboard no aparezcan duplicadas
"""

print("=== VERIFICACIÓN DE TARJETAS DEL DASHBOARD ===")
print()
print("Para verificar que las tarjetas no aparezcan duplicadas:")
print()
print("1. Abrir http://localhost:8080 en el navegador")
print("2. Abrir la consola del navegador (F12)")
print("3. Verificar que cada método de actualización se ejecute solo UNA vez:")
print("   - 'Updating tickets by movie chart...'")
print("   - 'Updating tickets by auditorium chart...'")
print("   - 'Loading dashboard data...'")
print()
print("4. Verificar visualmente que las tarjetas se vean así:")
print("   📊 Total de Ventas - 2 métricas")
print("   👥 Clientes - 1 métrica")
print("   🎟️ Boletos - 2 métricas") 
print("   🎬 Boletos por Película - Lista de películas (SIN duplicar)")
print("   🏛️ Boletos por Sala - Lista de salas (SIN duplicar)")
print("   🎭 Películas Destacadas - 2 secciones (Más vendida y Menos vendida)")
print()
print("5. Si todavía hay duplicación, ejecutar en la consola:")
print("   - runFullCheck() para diagnóstico completo")
print("   - reloadDashboard() para forzar recarga")
print()
print("CAMBIOS REALIZADOS:")
print("✅ Agregado flag isLoading para evitar cargas simultáneas")
print("✅ Modificado DOMContentLoaded para evitar carga duplicada")
print("✅ Agregados logs de debug para rastrear actualizaciones")
print("✅ Verificación de datos existentes antes de cargar")
print()
print("El problema de 'dobles cards' debería estar resuelto ahora.")
print("="*50)
